### ISSUE TITLE
How many checks are in GitLab scan

### ISSUE THREAD

**Issue by krzychurra** [aquasecurity/chain-bench#109]
Hello!
First of all I would like to say that I really appreciate your work to add support for GitLab. I know that currently chain-bench GitLab are in beta but how many checks are in GitLab scan now?

**Comment by morwn** [comment]
Hi @krzychurra,
currently, in beta 9 CIS checks have been implemented, you can see those [here](https://github.com/aquasecurity/chain-bench/blob/012229c4fe045511170adcd2ae2719024e7a70a8/internal/scm-clients/gitlab/adapter.go#L144)
