### ISSUE TITLE
Rego schema support

### ISSUE THREAD

**Issue by naortalmor1** [aquasecurity/chain-bench#17]
OPA version 0.41.0 supports schema enforcement - https://www.openpolicyagent.org/docs/v0.41.0/schemas.
Please add schema for the object that passes to the Rego files and define the schema of the returned value.

**Comment by morwn** [comment]
@naortalmor1 - could you please create new discussion under [Ideas tab](https://github.com/aquasecurity/chain-bench/discussions/categories/ideas)
