### ISSUE TITLE
odd tags

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/chain-bench#19]
## Description

Is there a reason for the non-release tags like `0.1.4+1`? Do they serve any purpose or can they be removed?

**Comment by naortalmor1** [comment]
It can be removed, probably related to the goreleaser.
@06kellyjac can you handle it?

**Comment by 06kellyjac** [comment]
I don't have tag deletion perms I'm afraid since I don't work for @aquasecurity 

https://github.com/aquasecurity/chain-bench/releases/tag/0.1.4%2B1

https://github.com/aquasecurity/chain-bench/tags

You might be able to, or maybe a repo admin will have to do that
(Also make sure to delete the tags on local clones before doing a `git push --tags` with a new release tag or they'll come back)

**Comment by morwn** [comment]
@06kellyjac thanks for raising this issue. I  remove those tags both remote and local
