### ISSUE TITLE
false positive when the endpoint is not accessible (e.g. not enough permissions)

### ISSUE THREAD

**Issue by rgreinho** [aquasecurity/chain-bench#32]
## Description

Running `./chain-bench scan --repository-url https://github.com/buildsec/frsca --access-token $GITHUB_TOKEN -o ./results`, some checks where marked as failed due to not having enough permissions associated with the GitHub token.

For instance:

```md
1.1.3 Ensure any change to code receives approval of two strongly authenticated
users Failed
```

The problem was that the GITHUB_TOKEN did not have permissions to read the branch protection settings, therefore marking this check as `failed`.

However it should in this case show another status, like `Unknown` or `not evaluated` for instance, as the check was not able to read the results (the endpoint returned a 404).

The `failed` status implies that the requirement was not met, and should be reserved for cases where the number of required reviewers was strictly less than 2.

The same problem applies to all the checks that returned a 404.

## Additional details in case it does not expose sensitive data (scanned pipeline files, PR, etc):

**Comment by naortalmor1** [comment]
@MorAlon1 Please take a look and fix it 🙏🏽

**Comment by MorAlon1** [comment]
@rgreinho can you please give us more details about the scenario? was it public repository or private and what permissions your token includes?

**Comment by rgreinho** [comment]
@MorAlon1 Yes, the project is open source, and you should be able to to reproduce the behavior by re-running the command I pasted above.  

The permissions for this particular token are:

- repo
- workflow
- admin:org -> read:org
- admin:repo_hook -> read:repo_hook 
- gist
- user
- project -> read:project

**Comment by MorAlon1** [comment]
@rgreinho  I created a token with the permissions you mentioned before and got Unknown for rule 1.1.3, can you check again if you gave me the right permissions?

**Comment by rgreinho** [comment]
Yup, this is what I get, from the main branch:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/6969134/176948133-8c633e05-3a48-47c7-b0fb-a6bac079d438.png">

**Comment by morwnbrg** [comment]
@rgreinho  - can you please check that the fix works for your case?

**Comment by rgreinho** [comment]
@MorAlon1 I just checked with the latest commit from the main branch and it did not seem to solve my issue:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/6969134/177355406-f0d8400d-51ba-4359-9821-2f7a487a844a.png">

But we do use 2 reviewer approvals in order for a PR to be merged. 

For instance with https://github.com/buildsec/frsca/pull/242, you can see that we needed an approval from me and from [bradbeck](https://github.com/bradbeck) before our bot ([kodiak](https://github.com/chdsbd/kodiak)).

If you want to re-open this PR, I'd be happy to help you dig.

**Comment by morwn** [comment]
@rgreinho I'm not sure how `kodiak` bot enforcing the policy. could you please enlighten me?
any case, we currently enforce the checks based on the branch protection API call: 
```
curl \
  -H "Accept: application/vnd.github+json" \ 
  -H "Authorization: token <TOKEN>" \
  https://api.github.com/repos/OWNER/REPO/branches/BRANCH/protection
```

so if `.required_pull_request_reviews.required_approving_review_count` < 2 we fail the check.
let me know if you set the `required_approving_review_count` corresponde

**Comment by rgreinho** [comment]
Sure thing! Kodiak uses the branch protection settings to decide when to merge or rebase a branch. Therefore as soon as all the branch protection criterias are met, the bot acts accordingly.  

Requiring 2 reviewers is part of our branch protection settings.

**Comment by morwn** [comment]
What do you get when you run this api call?

```
curl \
  -H "Accept: application/vnd.github+json" \ 
  -H "Authorization: token <TOKEN>" \
  https://api.github.com/repos/OWNER/REPO/branches/BRANCH/protection
```

**Comment by rgreinho** [comment]
```bash
curl -s  -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/buildsec/frsca/branches/main/protection
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-branch-protection"
}
```

and

```bash
$ curl -s  -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/buildsec/frsca/branches/main/protection/required_pull_request_reviews
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-pull-request-review-protection"
}
```

**Comment by morwn** [comment]
You might miss the permission for repo settings. please try to generate a scoped token based on an **admin user** within this repository

**Comment by rgreinho** [comment]
Here is a screenshot of the branch protection settings:

![image](https://user-images.githubusercontent.com/6969134/177402083-c91d1d93-119d-45e4-b285-902a2b8a024e.png)

**Comment by rgreinho** [comment]
@morwn It worked like a charm! Great job!

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/6969134/177572089-8831eab6-57e9-4e06-a1b8-ac397c327198.png">
