### ISSUE TITLE
Remediation instructions should be permalinks

### ISSUE THREAD

**Issue by rgreinho** [aquasecurity/chain-bench#35]
On the aquasec website listing the issues and their remediation, it is currently not possible to give a link pointing to the exact subsection.

For example, it is only possible to link the "Code Changes" (https://avd.aquasec.com/compliance/softwaresupplychain/cis-1.0/cis-1.0-sourcecode/1.1) page, but not to point directly to the "1.1.3 Ensure any change to code receives approval of two strongly authenticated users" item.

Then this permalink should be used in the "Url" value of the report file generated by chain-bench.

**Comment by naortalmor1** [comment]
@morwn Please take it with @owenrumney and see how we can extend AVD to include specific link target.
