### ISSUE TITLE
A GitHub Action support

### ISSUE THREAD

**Issue by morwn** [aquasecurity/chain-bench#41]
A GitHub Action would be very nice to be able to run it.

_Originally posted by @hazcod in https://github.com/aquasecurity/chain-bench/discussions/26_

**Comment by tomwillis608** [comment]
+1

**Comment by morwn** [comment]
thanks @itaywol  for your great contribution!. you can find the action [here](https://github.com/marketplace/actions/chain-bench-action) and the repository [here](https://github.com/aquasecurity/chain-bench-action)
