### ISSUE TITLE
Duplicate section heading in PDF

### ISSUE THREAD

**Issue by ThisIsMissEm** [aquasecurity/chain-bench#67]
## Description

I was reviewing the pdf of checks: https://github.com/aquasecurity/chain-bench/blob/main/docs/CIS-Software-Supply-Chain-Security-Guide-v1.0.pdf and noticed that for section 1.2, there's a duplication of the `1.2.2` value, so it reads as `1.2.2: 1.2.2 Name Of Check`

## What did you expect to happen?

n/a

## What happened instead?

n/a

## Additional details (base image name, container registry info...):

This is just for your information if you want to fix it, it causes no actual problems that I can see.

**Comment by naortalmor1** [comment]
Hi, thanks for letting us know that!
Working on it :)

**Comment by resheetk** [comment]
Hi,
We've opened a [ticket](https://workbench.cisecurity.org/tickets/15891?from=) in the guide [workbench](https://workbench.cisecurity.org/benchmarks/7555) and it will be fixed in the next version.
Thanks for letting us know!
