### ISSUE TITLE
CIS-Software-Supply-Chain-Security-Guide-v1.0.pdf link is broken

### ISSUE THREAD

**Issue by FrimIdan** [aquasecurity/chain-bench#74]
## Description

Clicking on https://github.com/aquasecurity/chain-bench/blob/main/docs/CIS-Software-Supply-Chain-Security-Guide-v1.0.pdf provide the following error

![image](https://user-images.githubusercontent.com/40820488/180770294-877a2a51-982a-4f59-833f-38b3f7513936.png)

**Comment by krol3** [comment]
Hi @FrimIdan! for me, it's working! do you still have problems?

**Comment by FrimIdan** [comment]
Now it is working, thanks @krol3
