### ISSUE TITLE
Show showing all columns in the CLI table

### ISSUE THREAD

**Issue by MartinPetkov** [aquasecurity/chain-bench#77]
The CLI format table has static columns, but the JSON results file has more data that is worth showing in the table, particularly "Remediation". Presumably the goal is for someone to see the results and try to improve them, and it's easier to see the remediation suggestions in table form than in JSON.

**Comment by naortalmor1** [comment]
Yep, today we have more fields in the JSON output than the table output because we want to keep the table as lean as possible and display only the run summary.
There are some long remediation instructions so it might hurt the table view.
