### ISSUE TITLE
Does not work with corporative repository

### ISSUE THREAD

**Issue by bret99** [aquasecurity/chain-bench#83]
It's OK with github.com for instance. But "panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb3ef3b]" with corporative gitlab repository even for admin with all token permissions.

**Comment by naortalmor1** [comment]
Hi @bret99,
Unfortunately, Gitlab integration is not supported yet.
We'll add this ability soon. 🙏🏽
